In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [6]:
flat = arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
flat[0]

1

In [10]:
flat[3: 6]

array([4, 5, 6])

In [11]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [12]:
flat[3:] # same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [20]:
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [21]:
b = flat[3:7].copy() # This is not a slice because we are using copy method to get the copy

In [22]:
b

array([444444,      5,      6,      7])

In [24]:
b[0] = 444444666

In [25]:
b

array([444444666,         5,         6,         7])

In [26]:
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [27]:
arr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [28]:
arr[[1, 4, 6]]

array([54,  2, 34])

In [30]:
arr[arr>23]

array([54, 53, 34])