In [1]:
import numpy as np
# Creating a 1D Numpy array
arr1 = np.array([1,2,3,4,5])
print(arr1)
# Creating a 2D Numpy array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
# Checking type and shape
print("Type:",type(arr1))
print("Shape:",arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.full((4,5),18)

array([[18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18]])

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.arange(0,100,11)

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [7]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [8]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [9]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [10]:
myarr.shape

(4, 3)

In [11]:
myarr.size

12

In [12]:
myarr.ndim

2

In [13]:
myarr.dtype

dtype('int64')

In [14]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]],dtype='float32')

In [15]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [16]:
myarr.dtype

dtype('float32')

In [20]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [17]:
n = myarr.astype('int32')

In [18]:
myarr.dtype

dtype('float32')

In [19]:
n.dtype

dtype('int32')

In [21]:
myarr.shape

(4, 3)

In [22]:
reshape = myarr.reshape((3,4))

In [23]:
reshape.shape

(3, 4)

In [24]:
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [25]:
 myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])