In [1]:
# create a 3X3 array filled random numbers and print its shape
import numpy as np 

In [3]:
arr = np.array([[1,2,4],[5,6,23],[56,45,255]])

In [4]:
arr

array([[  1,   2,   4],
       [  5,   6,  23],
       [ 56,  45, 255]])

In [5]:
arr.shape

(3, 3)

In [6]:
# convert an array of floats 

In [7]:
arr = np.array([1.1,2.2,3.3])

In [11]:
arr_int = arr.astype(np.int32)

In [12]:
arr_int

array([1, 2, 3], dtype=int32)

In [13]:
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [15]:
index = arr%2==0

In [17]:
arr[index]

array([2, 4, 6])

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [19]:
arr_reshaped = arr.reshape((3,3))

In [20]:
arr_reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Use boolean masking to filter numbers greater than 50 in an array.

In [22]:
arr = np.array([[100,45,78,89],[122,42,78,9]])

In [23]:
boolean = arr>50

In [24]:
arr[boolean]

array([100,  78,  89, 122,  78])

In [19]:
arr = np.arange(1,101)

In [20]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [21]:
arr.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
arr.size

100

In [22]:
arr.ndim

1

In [15]:
arr.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [16]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
 

In [17]:
arr.ndim

2