In [2]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [26]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]
